config/routes.rb
Rails.application.routes.draw do
  resource :team
  resources :meetings, only: :show do
    resources :statuses, except: [:index, :show]
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "teams#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :team
  has_many :statuses

  delegate :teammates, to: :team
  delegate :name, to: :team, prefix: :team

  enum time: [:morning, :afternoon]

  after_create :send_status_requests

  private
  def send_status_requests
    teammates.each do |teammate|
      StatusMailer.request_status(teammate, self).deliver_now
    end
  end
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :meeting
  belongs_to :teammate, class_name: 'User', foreign_key: 'user_id'

  validates_presence_of :message
  validates_uniqueness_of :meeting_id, scope: :user_id
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :master, class_name: 'User'
  has_many :teammates, class_name: 'User'
  has_many :meetings

  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :working_team, class_name: "Team", required: false, foreign_key: "team_id"
  has_one :managed_team, class_name: "Team", foreign_key: "master_id"
  has_many :statuses

  def team
    master ? managed_team : working_team
  end

  def manage? team
    managed_team == team
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  protected
=begin
    If user was created with a team token, then redirects them there;
    If user has no affiliation to a team yet, assume it's a new Scrum Master,
    and redirect to new team path.
=end
  def after_sign_up_path_for(resource)
    resource.team ? team_path : new_team_path
  end

  def after_sign_in_path_for(resource)
    resource.team ? team_path : new_team_path
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def show
    @meeting = current_user.team.meetings.find(params[:id])
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_meeting
  before_action :set_status, only: [:edit, :update, :destroy]
  before_action :check_if_teammate, only: [:new, :create]
  before_action :check_ownership, only: [:edit, :update, :destroy]

  # GET /statuses/new
  def new
    @status = @meeting.statuses.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = @meeting.statuses.new(status_params.merge(teammate: current_user))

    respond_to do |format|
      if @status.save
        format.html { redirect_to @meeting, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    def set_meeting
      @meeting = Meeting.find(params[:meeting_id])
    end

    def check_if_teammate
      redirect_to root_path unless current_user.in? @meeting.teammates
    end

    def check_ownership
      redirect_to root_path unless @status.teammate == current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:message)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :check_if_master, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_if_has_team, only: [:edit, :update, :destroy]

  # GET /team
  # GET /team.json
  def show
  end

  # GET /team/new
  def new
    if current_user.team
      redirect_to team_path, alert: "You already have a team."
    else
      @team = current_user.build_managed_team
    end
  end

  # GET /team/edit
  def edit
  end

  # POST /team
  # POST /team.json
  def create
    @team = current_user.build_managed_team(team_params)
    respond_to do |format|
      if @team.save
        format.html { redirect_to team_path, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team
  # PATCH/PUT /team.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to team_path, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team
  # DELETE /team.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to new_team_path, notice: 'Team was successfully destroyed. You need to create another one to continue using DailyManager' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = current_user.team
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name)
    end

    def check_if_master
      redirect_to team_path, alert: "You are not a Scrum Master." unless current_user.master?
    end

    def check_if_has_team
      redirect_to new_team_path, alert: "Please, create a team first." unless current_user.team
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title DailyManager
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if current_user
      nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top
        a.navbar-brand href="#" DailyManager
        button.navbar-toggler.navbar-toggler-right aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
          span.navbar-toggler-icon
        #navbar.collapse.navbar-collapse
          ul.navbar-nav.mr-auto
            li.nav-item
              = link_to "home", root_url, class: "nav-link"
          = link_to "logout", destroy_user_session_path, :method => :delete, :data => {:confirm => 'Are you sure?'}, class: "nav-link"
    .container role="main" style="padding: 80px"
      - if notice
        .alert.alert-info.alert-dismissible.fade.show role="alert"
          = notice
          button.close[type="button" data-dismiss="alert" aria-label="Close"]
            span[aria-hidden="true"]
              | ×
      - if alert
        .alert.alert-warning.alert-dismissible.fade.show role="alert"
          = alert
          button.close[type="button" data-dismiss="alert" aria-label="Close"]
            span[aria-hidden="true"]
              | ×
      = yield

app/views/meetings/show.html.slim
p#notice = notice

.col-sm-12
  p
    strong Team:
    = @meeting.team.name
  p
    strong Time:
    =< @meeting.time

  =< link_to 'Back', team_path

hr

- if @meeting.statuses.any?
  .col-sm-12
    h4 Messages
    table.table-bordered.table-hover
      thead
        tr
          th width="200" Teammate
          th width="600" Message

      tbody
        - @meeting.statuses.each do |status|
          tr
            td = status.teammate.email
            td = status.message

app/views/statuses/_form.html.slim
= simple_form_for([@meeting, @status]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :message

  .form-actions
    = f.button :submit

app/views/statuses/edit.html.slim
h1 Editing status

== render 'form'

=> link_to 'Show', @status
'|
=< link_to 'Back', statuses_path

app/views/statuses/new.html.slim
h1 New status

== render 'form'